---
- name: install nova packages
  yum: name="{{ packages }}" state=latest
  vars:
    packages:
    - openstack-nova-compute

- name: create nova configuration file
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: start libvirtd service
  service: name=libvirtd state=restarted enabled=yes

- name: start nova-compute service
  service: name=openstack-nova-compute state=restarted enabled=yes
