---
- name: install openstack package
  yum: name=openstack-dashboard state=latest

- name: create horizon configuration file
  template: src=local_settings.j2 dest=/etc/openstack-dashboard/local_settings

- name: create horizon httpd configuration file
  template: src=openstack-dashboard.conf.j2 dest=/etc/httpd/conf.d/openstack-dashboard.conf

- name: restart memcached service
  service: name=memcached state=restarted enabled=yes

- name: restart httpd service
  service: name=httpd state=restarted enabled=yes

