---
- name: install required packages
  yum: name="{{ packages }}" state=latest
  vars:
    packages:
    - MySQL-python
    - mariadb
    - mariadb-server
    - python2-PyMySQL

- name: configure mysql
  template: src=openstack.cnf.j2 dest=/etc/my.cnf.d/openstack.cnf
  notify: restart mysql

- name: start mysql
  service: name=mariadb state=started enabled=yes

- name: Sets the root password 
  mysql_user: user=root password="{{ root_dbpw }}" host=localhost

- name: Deletes anonymous MySQL server user for ansible_fqdn
  mysql_user: login_user=root login_password={{ root_dbpw }} user="" host="{{ ansible_fqdn }}" state="absent"

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: login_user=root login_password={{ root_dbpw }} user="" state="absent"

- name: Secures the MySQL root user for IPV6 localhost (::1)
  mysql_user: login_user=root login_password={{ root_dbpw }} user="root" password="{{ root_dbpw }}" host="::1"

- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: login_user=root login_password={{ root_dbpw }} user="root" password="{{ root_dbpw }}" host="127.0.0.1"

- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user: login_user=root login_password={{ root_dbpw }} user="root" password="{{ root_dbpw }}" host="localhost"

- name: Secures the MySQL root user for server_hostname domain
  mysql_user: login_user=root login_password={{ root_dbpw }} user="root" password="{{ root_dbpw }}" host="{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: login_user=root login_password={{ root_dbpw }} db=test state=absent