- name: install rabbitmq-server package
  yum: name=rabbitmq-server state=latest

- name: start rabbitmq-server service
  service: name=rabbitmq-server state=started enabled=yes

- name: Add User
  shell: rabbitmqctl add_user openstack {{ rabbitmq_pw }}

- name: Set Permission
  shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"