- name: Install .deb package from the internet.
  apt:
    pkg:
    - libsctp1
    
- name: Install .deb package from the internet.
  apt:
    deb: https://iperf.fr/download/ubuntu/libiperf0_3.7-3_amd64.deb

- name: Install .deb package from the internet.
  apt:
    deb: https://iperf.fr/download/ubuntu/iperf3_3.7-3_amd64.deb

- name: Run iperf3 server
  shell: iperf3 --server --daemon
