---
- name: Discover Host nova
  shell: nova-manage cell_v2 discover_hosts --verbose
  become: yes
  become_user: nova

- name: discover_hosts
  shell: source /root/admin_rc && nova-manage cell_v2 discover_hosts --verbose
